export const TEAMS = [
  {
    name: "CMS",
    members: [
      "Anh Huynh",
      "Triet Nguyen",
      "Duc Pham",
      "Tung Le",
      "Nhan Duc Bui",
      "Huy Vo",
      "Duc Truong",
      "Phuoc Vo",
      "Viet Pham",
      "Thang Nguyen",
      "Hieu Nguyen",
      "Dong Phung",
      "Linh Nguyen Truong",
      "Bach Pham",
      "Mien Pham",
      "Dung Tran",
    ],
  },
  {
    name: "PRO",
    members: [
      "Thang Do",
      "Ly Nguyen",
      "Van Nguyen",
      "Quang L�",
      "Nhut Do",
      "HNghia Nguyen",
      "Minh Ha",
      "Nghia Nguyen",
      "Dung Nguyen",
    ],
  },
  {
    name: "WEB",
    members: ["Hung Le", "Thanh Thao", "Minh Bui"],
  },
  {
    name: "ERP",
    members: ["Dung Thai", "Hoa Nguyen", "Huynh Do", "Hieu Khau"],
  },
  {
    name: "i3Website",
    members: ["Huy Nguyen", "Loc Pham", "Hien Bui", "Kieu Nguyen"],
  },
  {
    name: "Data Mining",
    members: ["Hoa Phan", "Thinh Thai"],
  },
  {
    name: "TESTER",
    members: [
      "Phuong Thanh",
      "Han Le",
      "Nguyen Cao",
      "Thuong Nguyen",
      "Lan Le",
      "Danh Nguyen",
      "Tam Vo",
      "Thuy Tran",
      "Hoa Tran",
      "Vy Tran",
      "Ngan Nguyen",
      "Thanh Bui",
      "Vu Pham",
      "Nhung Nguyen",
      "Khoa Hoang",
      "ThiThanh Nguyen",
      "Tran Nguyen",
    ],
  },
];
